"""change iamge_path to image_path in facial_detection_user_images table

Revision ID: 1dca75e49e52
Revises: c926fbc29c74
Create Date: 2025-05-23 16:26:57.600296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dca75e49e52'
down_revision: Union[str, None] = 'c926fbc29c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_detection_user_images', sa.Column('image_path', sa.String(), nullable=False))
    op.drop_column('facial_detection_user_images', 'iamge_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_detection_user_images', sa.Column('iamge_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('facial_detection_user_images', 'image_path')
    # ### end Alembic commands ###
