"""facial_detections table change the fullname into the user_id

Revision ID: a733c8bec63d
Revises: 1dca75e49e52
Create Date: 2025-05-26 16:48:21.076944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a733c8bec63d'
down_revision: Union[str, None] = '1dca75e49e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_id', table_name='todos')
    op.drop_table('todos')
    op.add_column('facial_detections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'facial_detections', 'users', ['user_id'], ['id'])
    op.drop_column('facial_detections', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_detections', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'facial_detections', type_='foreignkey')
    op.drop_column('facial_detections', 'user_id')
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='todos_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    # ### end Alembic commands ###
