"""update facial_detections table

Revision ID: aa182e1af623
Revises: fdca1378dfbe
Create Date: 2025-06-02 18:26:14.770702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa182e1af623'
down_revision: Union[str, None] = 'fdca1378dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_detections', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('facial_detections', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'facial_detections', 'subjects', ['subject_id'], ['id'])
    op.drop_column('facial_detections', 'time_in')
    op.drop_column('facial_detections', 'time_out')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_detections', sa.Column('time_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('facial_detections', sa.Column('time_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'facial_detections', type_='foreignkey')
    op.drop_column('facial_detections', 'status')
    op.drop_column('facial_detections', 'subject_id')
    # ### end Alembic commands ###
