"""add new table facial_detections_user_images and roles

Revision ID: c926fbc29c74
Revises: a88125628c7c
Create Date: 2025-05-16 16:55:31.161362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c926fbc29c74'
down_revision: Union[str, None] = 'a88125628c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facial_detection_user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('iamge_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('facial_detections', sa.Column('time_in', sa.DateTime(), nullable=True))
    op.add_column('facial_detections', sa.Column('time_out', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'section')
    op.drop_column('users', 'role_id')
    op.drop_column('facial_detections', 'time_out')
    op.drop_column('facial_detections', 'time_in')
    op.drop_table('facial_detection_user_images')
    op.drop_table('roles')
    # ### end Alembic commands ###
