"""new table student_infos and subjects table

Revision ID: fdca1378dfbe
Revises: a733c8bec63d
Create Date: 2025-06-02 05:25:17.610444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdca1378dfbe'
down_revision: Union[str, None] = 'a733c8bec63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campus', sa.String(), nullable=False),
    sa.Column('academic_term', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('student_number', sa.String(), nullable=False),
    sa.Column('lrn', sa.String(), nullable=False),
    sa.Column('year_status', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_info_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('lec_units', sa.String(), nullable=False),
    sa.Column('lab_units', sa.String(), nullable=False),
    sa.Column('days', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_info_id'], ['student_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_todos_id', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='todos_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    op.drop_table('subjects')
    op.drop_table('student_infos')
    # ### end Alembic commands ###
